# Generated by Django 3.1 on 2020-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instauser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
