# Generated by Django 3.1.2 on 2020-10-08 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instauser', '0002_auto_20201007_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='followers',
            field=models.ManyToManyField(default='self', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
